;Filename: camera.ini
;Author: Nico Hessenthaler
;Date: 2026-06-05
;Version: 1.0
;Description:
;    General camera parameters.
;License: Apache License Version 2.0
;Contact: nico.hessenthaler@hs-heilbronn.de

[ueye]
# bool: Continuous capture mode for the uEye camera. If set to True, the camera will continuously capture frames until stopped. 
# If set to False, the camera will allow the caputring of single frames.
# Default: True
continuous_capture = True

# tuple: Area of interest for cropping the camera image, in the format (x_min, y_min, width, height) live on the image sensor.
# Required to match the field of view of the event camera and the uEye camera due to different resolutions.
# Default: (220, 135, 1380, 780)
# Default 2: (0, 116, 1380, 780)
crop_aoi = (220, 135, 1380, 780)

# float: Exposure time for the uEye camera in milliseconds.
# Default: 20.0
# Unit: ms
exposure_time = 20.0

# int: Gain value for the uEye camera.
# Default: 70
# Unit: -
gain_value = 70

# int: Gamma value for the uEye camera. (100 corresponds to a gamma of 1.0, 200 corresponds to a gamma of 2.0, etc.)
# Gamma 1 is typically used for industrial applications, while gamma 2 is often used for consumer applications.
# The optimal gamma value depends on the specific use case and lighting conditions.
# Default: 100
# Unit: -
gamma_value = 100

# int: White balance red gain value for the uEye camera.
# Default: 18
# Unit: -
wb_red_gain = 18

# int: White balance green gain value for the uEye camera.
# Default: 0
# Unit: -
wb_green_gain = 0

# int: White balance blue gain value for the uEye camera.
# Default: 14
# Unit: -
wb_blue_gain = 14

# int: Horizontal resolution of the uEye camera in pixels.
# Default: 1380
# Unit: pixels
horizontal_resolution = 1380

# int: Vertical resolution of the uEye camera in pixels.
# Default: 780
# Unit: pixels
vertical_resolution = 780

# int: Channel of the uEye camera. 3 for color images (e.g. RGB) and 1 for grayscale images.
# Default: 3
# Unit: -
channel = 3

# int: Bits per pixel for the uEye camera.
# Default: 24
# Unit: bits/pixel
bits_per_pixel = 24

# int: Pixel clock frequency for the uEye camera in MHz. Required to be 40 MHz to achieve the desired frame rate of (30) fps with the given 
# resolution and bits per pixel.
# Supported frequencies are: (10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 
# 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 
# 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 104, 108, 112) MHz.
# Default: 50.0
# Unit: MHz
pixel_clock_frequency = 50

# float: Frames per second for the uEye camera.
# Default: 25.0
# Unit: fps
fps = 25.0

# int: Save only every nth frame from the uEye camera to reduce the load and amount of similar images. For example, if set to 5, only every 5th frame will be saved.
# Default: 5
# Unit: frames
nth_frame = 5

# float: Pixel size of the camera sensor in meters.
# Default: 4.5e-6
# Unit: m/pixel
pixel_size = 4.5e-6

# str: Name of the intrinsic parameters file to load for the uEye camera. The file should be located in the assets folder and start with "calibration_rgb_intrinsics_xxxx.json"
# Default: calibration_rgb_intrinsics.json
# Unit: -
intrinsics_file_name = calibration_rgb_intrinsics.json


[yolo]
# int: Image width in pixel to feed into the YOLO segmentation model. The image will be resized to this width while maintaining the aspect ratio before being fed into the model.
# Default: 800
# Unit: pixels
y26_input_width = 800

# int: Image height in pixel to feed into the YOLO segmentation model. The image will be resized to this height while maintaining the aspect ratio before being fed into the model.
# Default: 448
# Unit: pixels
y26_input_height = 448

# bool: Flag indicating whether dynamic export size shall be enabled or not.
# Default: False
# Unit: -
y26_export_dynamic = False

# int: Maximum batch size to be processed by the model.
# Default: 1
# Unit: -
y26_export_max_model_batch_size = 1

# bool: Flag indicating whether the export shall be performed in half precision (float16) or not.
# Default: True
# Unit: -
y26_export_half_size = True

# float: Confidence threshold for the YOLO segmentation model. Detections with confidence scores below this threshold will be discarded.
# Default: 0.25
# Unit: -
y26_confidence_thresh = 0.25

# float: IoU threshold for the YOLO segmentation model. This threshold is used during non-maximum suppression to filter out overlapping bounding boxes.
# Default: 0.45
# Unit: -
y26_iou_thresh = 0.2

# bool: Flag indicating whether to infer with the YOLO segmentation model in half precision (float16) or not.
# Default: True
# Unit: -
y26_half_precision = True

# bool: Flag indicating whether to verbosely print the model export process for the YOLO segmentation model or not.
# Default: False
# Unit: -
y26_verbose = False

# bool: Flag indicating whether to use class agnostic NMS for the YOLO segmentation model or not. If set to True, the NMS will be applied across all classes, 
# meaning that overlapping bounding boxes will be suppressed regardless of their predicted class labels.
# Default: False
# Unit: -
y26_class_agnostic_nms = False


[prophesee]
# int: Serial number of the camera to open.
# Default: 00050275
# Unit: -
serial_number = 00050275

# int: Number of channels to use for displaying the events.
# Default: 3
# Unit: -
channels = 3

# str: Firmware version of the Prophesee camera.
# Default: 3.0.0
# Unit: -
firmware_version = 3.0.0

# str: Generation of the used hardware.
# Default: 4.0
# Unit: -
hardware_generation = 4.0

# str: Integrator name of the camera housing (e.g. Prophesee, Senso, IDS etc.).
# Default: Prophesee
# Unit: -
integrator_name = Prophesee

# int: Horizontal resolution of the camera in pixels.
# Default: 1280
# Unit: pixels
horizontal_resolution = 1280

# int: Vertical resolution of the camera in pixels.
# Default: 720
# Unit: pixels
vertical_resolution = 720

# float: Pixel size of the camera sensor in meters.
# Default: 4.86e-6
# Unit: m/pixel
pixel_size = 4.86e-6

# str: Name of the camera settings file to load for the Prophesee camera.
# If the filename contains "stereo_calibration", event undistortion is automatically disabled.
# Default: settings_prophesee_conveyor.json
settings_file_name = settings_prophesee_conveyor.json

# str: Name of the intrinsic parameters file to load for the Prophesee camera. The file should be located in the assets folder and start with "calibration_event_intrinsics_xxxx.json"
# Default: calibration_event_intrinsics.json
intrinsics_file_name = calibration_event_intrinsics.json

# float: Mask scaling factor for projections from the RGB camera to the event camera.
# Default: 1.1
# Unit: -
mask_scaling_factor = 1.125