;Filename: camera.ini
;Author: Nico Hessenthaler
;Date: 2026-06-05
;Version: 1.0
;Description:
;    General camera parameters specifically for stereo calibration (overwrite standard parameters).
;License: Apache License Version 2.0
;Contact: nico.hessenthaler@hs-heilbronn.de

[ueye]
# float: Exposure time for the uEye camera in milliseconds.
# Default: 100.0
# Unit: ms
exposure_time = 100.0

# int: Gain value for the uEye camera.
# Default: 85
# Unit: -
gain_value = 100

# float: Frames per second for the uEye camera.
# Default: 10.0
# Unit: fps
fps = 10.0

# str: Intrinsic calibration file name for the Prophesee camera. This file contains parameters required for the intrinsic calibration process.
# Default: intrinsic_calibration_12mm_prophesee.ini
# Unit: -
intrinsic_calibration_file_name = intrinsic_calibration_12mm_ueye.ini


[prophesee]
# str: Name of the camera settings file to load for the Prophesee camera.
# Default: settings_prophesee_conveyor.json
# Unit: -
settings_file_name = settings_prophesee_stereo_calibration.json

# str: Intrinsic calibration file name for the Prophesee camera. This file contains parameters required for the intrinsic calibration process.
# Default: intrinsic_calibration_12mm_prophesee.ini
# Unit: -
intrinsic_calibration_file_name = intrinsic_calibration_12mm_prophesee.ini