;Filename: gui.ini
;Author: Nico Hessenthaler
;Date: 2026-06-05
;Version: 1.0
;Description:
;    General GUI parameters.
;License: Apache License Version 2.0
;Contact: nico.hessenthaler@hs-heilbronn.de

[data_capture]
# int: Width of the image containers in the data capture GUI.
# Default: 810
# Unit: pixels
image_width = 810

# int: Height of the image containers in the data capture GUI.
# Default: 540
# Unit: pixels
image_height = 540

# int: Height of the image display area in the data capture GUI due to a different aspect ration of the uEye camera and the event camera.
# Default: 455
# Unit: pixels
image_display_height = 455

# int: Size of the shared memory buffers for the base64 encoded event frames and RGB frames, allowing for live updates in the GUI.
# Default: 2000000
# Unit: bytes
b64_shared_memory_size = 2_000_000

# int: Size of the shared memory buffers for the raw event frames and RGB frames, allowing for live updates in the GUI.
# Default: 10000000
# Unit: bytes
raw_shared_memory_size = 10_000_000
