;Filename: stereo_calibration.ini
;Author: Nico Hessenthaler
;Date: 2026-06-05
;Version: 1.0
;Description:
;    Parameters required for stereo calibration.
;License: Apache License Version 2.0
;Contact: nico.hessenthaler@hs-heilbronn.de


[target]
# int: Target rows of the calibration target pattern (e.g. ChArUco).
# Default: TBD
# Unit: -
target_rows = TBD

# int: Target columns of the calibration target pattern (e.g. ChArUco).
# Default: TBD
# Unit: -
target_columns = TBD

# float: Size of a square in the calibration target pattern displayed on a monitor.
# Default: TBD
# Unit: m
target_square_size = TBD

# float: Fraction of the target square size that is used as marker size in the ChArUco board.
# Default: TBD
# Unit: -
target_marker_size_fraction = TBD

# str: Name of the window displaying the calibration target.
# Default: Calibration Target
# Unit: -
target_window_title = Calibration Target

# str: File name of the bitmap image of the calibration target to be displayed during the Arduino generation process.
# Default: charuco_bitmap.h
# Unit: -
target_bitmap_file_name = charuco_bitmap.h

# str: File name of the video showing the toggling calibration target to be displayed on e.g. a smartphone.
# Default: toggling_board.mp4
# Unit: -
target_video_file_name = toggling_board.mp4

# int: Bitmap height of the calibration target for Arduino displays.
# Default: 320
# Unit: pixels
target_bitmap_height = 320

# int: Bitmap width of the calibration target for Arduino displays.
# Default: 320
# Unit: pixels
target_bitmap_width = 400

# int: Display height of the calibration target.
# Default: 300
# Unit: pixels
target_display_height = 480

# int: Display width of the calibration target.
# Default: 300
# Unit: pixels
target_display_width = 640

# float: Alpha value for the dimmed calibration target image (between 0 and 1).
# Default: 0.5
# Unit: -
target_dim_alpha = 0.5

# int: Target margin in pixels for the calibration target pattern displayed on a monitor.
# Default: 10
# Unit: pixels
target_margin = 10

# float: Video duration in seconds for the toggling calibration target video.
# Default: 10
# Unit: seconds
target_video_duration = 10

# int: Frame rate for the toggling calibration target video.
# Default: 30
# Unit: frames per second
target_video_fps = 30

# int: Toggling frequency in Hz for the calibration target pattern.
# Default: 15
# Unit: Hz
target_frequency = 15


[ur5e]
# str: IP address of the UR5e robotic arm.
# Default: TBD
# Unit: -
robot_ip = TBD

# int: Primary port for communication with the UR5e robotic arm.
# Default: 30001
# Unit: -
primary_port = 30001

# int: Secondary port for communication with the UR5e robotic arm.
# Default: 29999
# Unit: -
secondary_port = 29999

# float: Time until the robot actually shows no movement after sending the stop command during the calibration process.
# Default: 1.0
# Unit: seconds
stop_command_delay = 2.5

# int: Number of interpolation steps for diagonal and extra position sweeps performed by the robot arm.
# Controls how many intermediate poses are generated between the start and end point of each sweep.
# Default: 4
# Unit: -
sweep_steps = 4


[recording]
# float: Interval between two captures during the calibration process in seconds.
# Default: 7.0
# Unit: seconds
capture_interval = 7.0

# str: Name of the file to store the intrinsic parameters of the RGB camera.
# Default: rgb_intrinsics.json
# Unit: -
rgb_intrinsics_file_path = calibration_rgb_intrinsics.json

# str: Name of the file to store the intrinsic parameters of the event camera.
# Default: event_intrinsics.json
# Unit: -
event_intrinsics_file_path = calibration_event_intrinsics.json

# str: Name of the file to store the extrinsic parameters between the RGB and event camera.
# Default: extrinsics.json
# Unit: -
extrinsics_file_path = calibration_extrinsics.json


[calibration]
# int: Minimum number of valid corner detections required for performing the calibration.
# Default: 50
# Unit: -
min_corners_for_calibration = 5

# float: Reprojection error threshold for filtering out frames during the calibration process.
# Default: 0.75
# Unit: pixels
reprojection_error_threshold = 0.75
